name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Generate test report
      run: npm run test:cov
      
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: ./boycott-kanye/bk-backend/coverage

  backend-build:
    runs-on: ubuntu-latest
    needs: backend-test
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-dist
        path: ./boycott-kanye/bk-backend/dist

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-test
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: ./boycott-kanye/bk-frontend/dist 