name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create mock environment for tests
      run: |
        echo "Creating test environment with mocks..."
        echo "POCKETBASE_URL=http://mock-pocketbase" > .env.test
        echo "POCKETBASE_ADMIN_EMAIL=test@example.com" >> .env.test
        echo "POCKETBASE_ADMIN_PASSWORD=testpassword" >> .env.test
        echo "NODE_ENV=test" >> .env.test
    
    - name: Run all tests
      run: npm test
    
    - name: Generate test coverage
      run: npm run test:cov
      
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: ./boycott-kanye/bk-backend/coverage

  backend-build:
    runs-on: ubuntu-latest
    needs: backend-test
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-dist
        path: ./boycott-kanye/bk-backend/dist

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create test setup file
      run: |
        echo "Creating Vue test setup file..."
        mkdir -p tests/setup
        cat > tests/setup/test-env.js << 'EOF'
        // Mock localStorage
        global.localStorage = {
          getItem: jest.fn(),
          setItem: jest.fn(),
          removeItem: jest.fn()
        };
        
        // Mock window.fetch
        global.fetch = jest.fn(() => 
          Promise.resolve({
            ok: true,
            json: () => Promise.resolve({ user: { id: 'test-user', name: 'Test User' } })
          })
        );
        
        // Mock Vue composition API auth module
        jest.mock('@/composables/useAuth', () => ({
          useAuth: () => ({
            isLoggedIn: { value: false },
            user: { value: null },
            login: jest.fn(),
            logout: jest.fn(),
            register: jest.fn()
          })
        }));
        EOF
        
        # Update jest.config.js to use setup file
        if grep -q "setupFiles" jest.config.js; then
          sed -i "s|setupFiles:.*|setupFiles: ['<rootDir>/tests/setup/test-env.js'],|" jest.config.js
        else
          sed -i "/module.exports/a \  setupFiles: ['<rootDir>/tests/setup/test-env.js']," jest.config.js
        fi
    
    - name: Run all tests
      run: npm test

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-test
    defaults:
      run:
        working-directory: ./boycott-kanye/bk-frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './boycott-kanye/bk-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: ./boycott-kanye/bk-frontend/dist 